packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: 5.9.2
  tsx: 4.20.6
  '@types/node': 22.15.3

  eslint: 9.39.1

  react: 19.2.0
  react-dom: 19.2.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2

  dotenv: 17.2.3
  dotenv-cli: 11.0.0
